name: ntpdate-snap
base: core20
version: '2.0'
summary: A Simple ntpdate in snap
description: |
        This is a simple ntpdate in snap
        
grade: stable 
confinement: strict 

layout:
  /etc/services:
    bind-file: $SNAP/etc/services
  /var/lib/sntp:
    bind: $SNAP_DATA/var/lib/sntp

apps:
  ntpdate-daemon:
    command: ntpdate-wrapper.sh
    daemon: simple
    restart-condition: always
    restart-delay: 30s
    plugs: [network, network-bind, time-control]

  ntpdate-snap:
    command: usr/bin/sntp
    plugs: [network, network-bind, time-control]

parts:
  ntpdate-daemon:
    plugin: nil
    stage-packages:
            - sntp

  common:
    plugin: dump
    source: .
